query GetCustomerById($id: Int!){
  customers (where: {id: { eq: $id}}){
    id
    firstName
    lastName
    contactNumber
    email
    address {
      adressLine1
      adressLine2
      city
      state
      country
    }
    orders {
      id,
      orderDate
      description
      totalmount
      depositAmount
      isDelivery
      status
      otherNotes
      customer {
        id
        firstName
        lastName
      }
    }
  }
}